AWSTemplateFormatVersion: 2010-09-09
Description: Abdullah Jimoh / Practice - This template deploys a VPC
Resources:
  PracticeVPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: "true"
      Tags:
        - Key: name
          Value: firstCfVPC
